In [219]:
#1. PRIME CLUSTERS

In [221]:
import numpy as np


In [223]:
arr = np.array ([[2, 3, 5], [4, 6, 8], [11, 13, 17], [7, 10, 13]])

In [225]:
def prime(n):
    if n < 2:
        return False
    if n in (2, 3):
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i+2) == 0:
            return False
        i += 6
    return True

In [227]:
def containsPrime(arr):
    prime_mask = np.vectorize(prime)(arr)
    return arr[np.any(prime_mask, axis=1)]

In [229]:
print(containsPrime(arr))

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [231]:
#2. LET"S PLAY CHECKERS

In [233]:
#2.1 Only Zeros

In [235]:
def checkerboard():
    return np.zeros((8, 8), dtype = int)

In [237]:
print(checkerboard())

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [239]:
#2.2 Odd Rows Alternating

In [241]:
def checkerboard():
    board = np.zeros((8, 8), dtype = int)
    board [::2, ::2] = 1
    return board

In [243]:
print(checkerboard())

[[1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]]


In [245]:
#2.3 Even Rows also Alternating

In [247]:
def checkerboard():
    board = np.zeros((8, 8), dtype = int)
    board [::2, ::2] = 1
    board [1::2, 1::2] = 1
    return board

In [249]:
print(checkerboard())

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [251]:
#2.4 Full Checkerboard Starting with Zero Instead

In [253]:
def reversecheckerboard():
    board = np.ones((8,8), dtype = int)
    board [::2, ::2] = 1
    board [1::2, 1::2] = 1
    return board

In [255]:
print (reversecheckerboard())

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [257]:
#3. THE EXPANDING UNIVERSE

In [259]:
universe = np.array(["galaxy", "clusters"])

In [261]:
def expansion(arr, spaces):
    return np.array ([" ".join(list(word)).replace(" "," " * spaces) for word in arr])

In [263]:
print (expansion(universe, 1))

['g a l a x y' 'c l u s t e r s']


In [265]:
print (expansion(universe, 2))

['g  a  l  a  x  y' 'c  l  u  s  t  e  r  s']


In [267]:
#4. SECOND-DIMMEST STAR

In [269]:
np.random.seed(123)
stars = np.random.randint (500, 2000, (5,5))
print (stars)

[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]


In [271]:
def secondDimmest(stars):
    return np.sort(stars, axis = 0)[1]

In [273]:
print (secondDimmest(stars))

[ 611 1108 1732 1346  724]
